### ISSUE TITLE
client.meta.users

### ISSUE THREAD

**Issue by bitxpert** [Skookum/bamboozled#36]
Hi
Following function is not working as expected.

client.meta.users

Getting this exception from gem
NoMethodError: undefined method `[]' for nil:NilClass
	from /home/zee/.rvm/gems/ruby-2.3.3/gems/bamboozled-0.1.0/lib/bamboozled/api/meta.rb:8:in `block (2 levels) in <class:Meta>'
	from (irb):280

Hope you will fix it

Thanks

**Comment by jonmagic** [comment]
I ran into this today so I cloned the gem and added a `binding.pry` [here](https://github.com/Skookum/bamboozled/blob/96b837a51cf45ec0dbc84827337d71df3acf080e/lib/bamboozled/api/meta.rb#L7) so I could inspect the returned results:

```ruby
module Bamboozled
  module API
    class Meta < Base

      [:field, :table, :list, :user].each do |action|
        define_method("#{action}s") do
          result = request(:get, "meta/#{action}s")
          require "pry"; binding.pry
          result["#{action}s".to_sym][action]
        end
      end

    end
  end
end
```

I then tested each of the defined methods and found:

* `client.meta.fields` returns an Array and will not work with `result["#{action}s".to_sym][action]`
* `client.meta.tables` errors out for me with an invalid date error in the xml parser, could be something to do with my companies Bamboo setup. Anyways, couldn't figure out what the result shape looks like [but according to the docs](https://www.bamboohr.com/api/documentation/metadata.php) it should be nested such that `result["#{action}s".to_sym][action]` would work.
* `client.meta.lists` works as advertised with `result["#{action}s".to_sym][action]`.
* `client.meta.users` returns a Hash keyed by the id value of the user, so this will not work with `result["#{action}s".to_sym][action]`.

I'm going to cut a PR that fixes `client.meta.fields` and `client.meta.users`. Probably won't have tests in my first draft of the PR because I want to just get a commit out there I can test manually with.

**Comment by bitxpert** [comment]
Bamboo hr api has no any explanation about this.
I need confirmation that is this 'client.meta.users' return all users in a company including terminated,deleted as well?

**Comment by bitxpert** [comment]
@mjording 
Here is an example to get terminated employee.
I've test but not getting terminated users.

https://github.com/Skookum/bamboozled/blob/master/examples/employees_over_time.rb
